modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="coal_craftsman"
version="0.1.1"
displayName="Coal CraftsMan"
credits="null"
displayURL="https://mcreator.net"
authors="HLFT"

[[dependencies.coal_craftsman]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




